UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index' WHERE predictor = 'VGM8 Index';

UPDATE raw_all_trades_dependents SET predictor = 'XLF US Equity', industry = 'Banks' WHERE symbol = 'UBS US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLF US Equity', industry = 'Banks' WHERE symbol = 'CS US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLV US Equity', industry = 'Drugs' WHERE symbol = 'NVS US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'SMM9 Index', industry = 'Industrials Diversified' WHERE symbol = 'ABB US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'SMM9 Index', industry = 'Luxury Goods Mining' WHERE symbol = 'SIG US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'SMM9 Index', industry = 'Technology' WHERE symbol = 'LXFT US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'SMM9 Index', industry = 'Autos' WHERE symbol = 'GTX US Equity';

UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = '' WHERE symbol = 'SKM US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'SMH US Equity', industry = 'Semiconductors' WHERE symbol = 'UMC US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'QQQ US Equity', industry = 'Technology' WHERE symbol = 'ATHM US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'QQQ US Equity', industry = 'Technology' WHERE symbol = 'BITA US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = 'Consumer Cyclical Retail' WHERE symbol = 'BABA US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLF US Equity', industry = 'Banks' WHERE symbol = 'MFG US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = 'Power' WHERE symbol = 'KEP US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = 'Autos' WHERE symbol = 'TM US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = 'Autos' WHERE symbol = 'HMC US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLF US Equity', industry = 'Banks' WHERE symbol = 'KB US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = '' WHERE symbol = 'WIT US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLF US Equity', industry = 'Banks' WHERE symbol = 'NMR US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = '' WHERE symbol = 'PKX US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = 'Basic Materials Metals' WHERE symbol = 'VEDL US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = 'Technology' WHERE symbol = 'INFY US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = 'Telecom' WHERE symbol = 'TLK US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = '' WHERE symbol = 'TTM US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = 'Electronics' WHERE symbol = 'AUO US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLV US Equity', industry = 'Drugs' WHERE symbol = 'TAK US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = '' WHERE symbol = 'CAJ US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'SMH US Equity', industry = 'Semiconductors' WHERE symbol = 'TSM US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = '' WHERE symbol = 'WNS US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'QQQ US Equity', industry = 'Electronics' WHERE symbol = 'SNE US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = '' WHERE symbol = 'CHT US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = 'Telecom' WHERE symbol = 'PHI US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = '' WHERE symbol = 'LPL US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLF US Equity', industry = 'Banks' WHERE symbol = 'HDB US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLF US Equity', industry = 'Banks' WHERE symbol = 'MUFG US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLF US Equity', industry = 'Banks' WHERE symbol = 'IBN US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = 'Shipping' WHERE symbol = 'DHT US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = 'Telecom' WHERE symbol = 'KT US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = 'Consumer Electronics' WHERE symbol = 'FN US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = 'Media Diversified' WHERE symbol = 'EROS US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'NHM9 Index', industry = 'Technology' WHERE symbol = 'SE US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLV US Equity', industry = 'Healthcare' WHERE symbol = 'RDY US Equity';

UPDATE raw_all_trades_dependents SET predictor = 'GXM9 Index', industry = 'Healthcare' WHERE symbol = 'FMS US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLF US Equity', industry = 'Banks' WHERE symbol = 'DB US Equity';


UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Telecom' WHERE symbol = 'ORAN US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Airplanes' WHERE symbol = 'AER US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLF US Equity', industry = 'Banks' WHERE symbol = 'ING US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Telecom' WHERE symbol = 'TEF US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = '' WHERE symbol = 'NVO US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'QQQ US Equity', industry = 'Technology' WHERE symbol = 'NOK US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLF US Equity', industry = 'Banks' WHERE symbol = 'SAN US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Shipping' WHERE symbol = 'SALT US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLV US Equity', industry = 'Drugs' WHERE symbol = 'TEVA US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = '' WHERE symbol = 'QGEN US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Consumer Products' WHERE symbol = 'UN US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Shipping' WHERE symbol = 'EURN US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = '' WHERE symbol = 'MBT US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Beverages' WHERE symbol = 'BUD US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = '' WHERE symbol = 'PHG US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = '' WHERE symbol = 'BBVA US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Software' WHERE symbol = 'SAP US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = '' WHERE symbol = 'SBGL US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = '' WHERE symbol = 'FMS US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Autos' WHERE symbol = 'RACE US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Autos' WHERE symbol = 'VNE US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Building Materials' WHERE symbol = 'CRH US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = '' WHERE symbol = 'SFL US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = '' WHERE symbol = 'FRO US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'SMH US Equity', industry = 'Semiconductors' WHERE symbol = 'STM US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = '' WHERE symbol = 'LIQT US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = '' WHERE symbol = 'STNG US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Gold' WHERE symbol = 'HMY US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Semiconductors' WHERE symbol = 'MX US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'QQQ US Equity', industry = 'Technology' WHERE symbol = 'SPOT US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'GDX US Equity', industry = 'Gold Mining Metals' where symbol = 'AU US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Packaged Foods / Consumer' where symbol = 'ANFI US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Basic Materials Aluminum' where symbol = 'CSTM US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Shipping Tankers' WHERE symbol = 'NAT US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Steel' WHERE symbol = 'MT US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'QQQ US Equity', industry = 'Technology' WHERE symbol = 'INXN US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Telecom' WHERE symbol = 'TKC US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLF US Equity', industry = 'Banks' WHERE symbol = 'AEG US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Autos' WHERE symbol = 'ADNT US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Telecom' WHERE symbol = 'I US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Basic Materials Specialty Chemicals' WHERE symbol = 'OEC US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'VGM9 Index', industry = 'Autos' WHERE symbol = 'ALV US Equity';


UPDATE raw_all_trades_dependents SET predictor = 'Z M9 Index', industry = '' WHERE symbol = 'PUK US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'Z M9 Index', industry = '' WHERE symbol = 'IHG US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'Z M9 Index', industry = 'Telecom' WHERE symbol = 'BT US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'Z M9 Index', industry = 'Tobacco' WHERE symbol = 'BTI US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLF US Equity', industry = 'Banks' WHERE symbol = 'BCS US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLF US Equity', industry = 'Banks' WHERE symbol = 'LYG US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLV US Equity', industry = 'Drugs' WHERE symbol = 'AZN US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'Z M9 Index', industry = 'Mining' WHERE symbol = 'RIO US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'OIH US Equity', industry = 'Oil' WHERE symbol = 'BP US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'Z M9 Index', industry = 'Utilities' WHERE symbol = 'NGG US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'Z M9 Index', industry = 'Scientific Publishing' WHERE symbol = 'RELX US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'Z M9 Index', industry = 'Medical Equipment' WHERE symbol = 'SNN US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLF US Equity', industry = 'Banks' WHERE symbol = 'HSBC US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLF US Equity', industry = 'Banks' WHERE symbol = 'RBS US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'Z M9 Index', industry = 'Leisure Cruises' WHERE symbol = 'CUK US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'Z M9 Index', industry = 'Farm & Constructin Equipment' WHERE symbol = 'CNHI US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLV US Equity', industry = 'Drugs' WHERE symbol = 'GSK US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'Z M9 Index', industry = 'Beverages' WHERE symbol = 'DEO US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'Z M9 Index', industry = 'Advertising' WHERE symbol = 'WPP US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'Z M9 Index', industry = '' WHERE symbol = 'PSO US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'Z M9 Index', industry = '' WHERE symbol = 'IGT US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'Z M9 Index', industry = '' WHERE symbol = 'NOMD US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'Z M9 Index', industry = '' WHERE symbol = 'UL US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'Z M9 Index', industry = 'Diversified Industrials' WHERE symbol = 'LXFR US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'GDX US Equity', industry = 'Gold' WHERE symbol = 'GFI US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'Z M9 Index', industry = 'Luxury Goods' WHERE symbol = 'FTCH US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'Z M9 Index', industry = 'Autos' WHERE symbol = 'FCAU US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'XLF US Equity', industry = 'Banks' WHERE symbol = 'JHG US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'Z M9 Index', industry = 'Autos' WHERE symbol = 'DLPH US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'QQQ US Equity', industry = 'Technology' WHERE symbol = 'MFGP US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'Z M9 Index', industry = 'Specialty Chemicals Basic Materials' WHERE symbol = 'LIN US Equity';

UPDATE raw_all_trades_dependents SET predictor = 'OIH US Equity', industry = 'Oil' WHERE symbol = 'TOT US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'OIH US Equity', industry = 'Oil' WHERE symbol = 'SDRL US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'OIH US Equity', industry = 'Oil' WHERE symbol = 'RIG US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'OIH US Equity', industry = 'Oil' WHERE symbol = 'E US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'OIH US Equity', industry = 'Oil' WHERE symbol = 'LPG US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'OIH US Equity', industry = 'Oil' WHERE symbol = 'NE US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'OIH US Equity', industry = 'Oil' WHERE symbol = 'SLB US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'OIH US Equity', industry = 'Oil' where symbol = 'CLB US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'OIH US Equity', industry = 'Oil' WHERE symbol = 'SMFG US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'OIH US Equity', industry = 'Oil' WHERE symbol = 'SSL US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'OIH US Equity', industry = 'Oil' WHERE symbol = 'RDS/A US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'OIH US Equity', industry = 'Oil' WHERE symbol = 'RDS/B US Equity';

UPDATE raw_all_trades_dependents SET predictor = 'EWA US Equity', industry = 'Banks' WHERE symbol = 'WBK US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'ESM9 Index', industry = 'Mining Metals Minerals' WHERE symbol = 'BHP US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'ESM9 Index', industry = 'Healthcare' WHERE symbol = 'MTD US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'ESM9 Index', industry = 'Cruises Leisure' WHERE symbol = 'RCL US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'GDX US Equity', industry = 'Mining Metals Minerals' where symbol = 'BBL US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'ESM9 Index', industry = 'Autos' where symbol = 'FLY US Equity';
UPDATE raw_all_trades_dependents SET predictor = 'ESM9 Index', industry = 'Business Services' where symbol = 'G US Equity';
